jwikman/nab-al-tools

- HowToContribute.md
- README.md
- src/PowerShell.ts
- tsconfig.json
Documented the necessary steps to get this project up and running on my PCs.
Of course there could be some parts missing due to already being installed on my systems (Win10, Ubuntu 19.04). Found a small "error" due to casing on linux.
My feelings won't get hurt if you don't accept my guide ;)
> Contributions suggestion

- src/WorkspaceFunctions.ts
> Removing invalid file system chars from appname. 

- snippets/misc.json
Makes building an enum object less annoying :)
> New (better) snippet for declaring enum values.

- CONTRIBUTING.md
- README.md
* Readme updated and linted. Table of contents added.
* CONTRIBUTING.md extended with information and guidelines.
Please squash merge this. Had some problems with gitconfig and anchor links.
> Add CONTRIBUTING.md & Better readme

- src/LanguageFunctions.ts
- src/XlfFunctions.ts
Fixes #12 .
* New function FindClosestMatch. Reads file once and performs a search for all strings in the provided string array. Returns the result for the string closest position to the cursor position.
* Removed unnecessary if statement on L28 and moved the lines into the else block above. -1 CC 👍 
* Removed previously added functions FindNextUntranslatedByToken & FindNextUntranslatedByState as FindClosestMatch makes them obsolete. 
* Removed export and renamed targetStateActionNeededAsList as it's not called out of that scope anymore. Seemed like good housekeeping since I just added it.
* Added GetTargetStateActionNeedKeywordList()
I'm quite proud of this solution so I really hope you find something to comment on or else i'm in the risk zone for hubris ;)
> Issue #23 Improving FindNextUntranslatedByToken

- CHANGELOG.md
- README.md
- package.json
- src/LanguageFunctions.ts
- src/NABfunctions.ts
- src/Settings.ts
New setting, SearchOnlyXlfFiles, to enable the *.xlf filter.
Solves #26
> Setting for Find in Files *.xlf filter

- CHANGELOG.md
- README.md
- package.json
- src/LanguageFunctions.ts
- src/NABfunctions.ts
- src/extension.ts
- Added function NAB: Find multiple targets in XLF files
- Added documentation
> FindMultipleTargets

- src/ALObject.ts
- src/NABfunctions.ts
- src/WorkspaceFunctions.ts
- src/test/ALObjectTestLibrary.ts
- src/test/AlFunctions.test.ts
Fixes #36, support interface objects and implements statements
> #36 Support for interfaces

- CHANGELOG.md
- README.md
- package.json
- src/NABfunctions.ts
- src/PowerShellFunctions.ts
- src/ToolTipsFunctions.ts
- src/extension.ts
> Suggest Tooltip

- .github/workflows/node.js.yml
Automates build and test runner on push and PR against master branch.
Uses [gabrielbb/xvfb-action](https://github.com/marketplace/actions/gabrielbb-xvfb-action) to run headless tests.
Runs test on latest versions of Windows, macOS and Ubuntu.
Tests with Node.js version 10.x, 12.x, 14.x
> Node.js workflow

- src/XLIFFDocument.ts
- src/XLIFFInterface.ts
- src/XmlFormatter.ts
- src/test/XLIFFTypes.test.ts
- src/test/XmlFormatter.test.ts
Classes and interfaces to enable simple serializing/deserializing of Xliff documents.
> Xliff types

- src/Levenshtein.ts
- src/test/Levenshtein.test.ts
Originally wrote this as part of the solution for issue #13 . Seems like a shame to let it go to waste :)
Function `MatchStringAgainstListOfStrings(..)` does what the name implies and let's you adjust the returned result by the threshold parameter. Depending on how much of a fuzzy match you want.
Rewritten from one of my old Python which in its turn was written of and modified from an article of the interwebs. The performance and results equal the Python code.
Also it has regression tests!
> Fuzzy string matching lehvenstein functions

- CODING_GUIDELINES.md
- CONTRIBUTING.md
- Add coding guidelines to aid contributors and code reviewers
> Coding guidelines

- extension/src/XLIFFDocument.ts
- extension/src/test/XLIFFTypes.test.ts
Fixes #43 with a workaround as a regex replacements of > in texts
> Fix #43 with > in texts

- extension/CHANGELOG.md
- extension/README.md
- extension/package.json
- extension/src/ALObject.ts
- extension/src/LanguageFunctions.ts
- extension/src/NABfunctions.ts
- extension/src/extension.ts
- extension/src/test/ALObjectTestLibrary.ts
- extension/src/test/AlFunctions.test.ts
- extension/src/test/LanguageFunctions.test.ts
- nab-al-tools.code-workspace
- New feature, "Update all XLF files"
- Runs the feature `NAB: Update g.xlf` followed by `NAB: Refresh XLF files from g.xlf`
- A couple of small fixes
> NAB: Update all XLF files

- dev-tools/fetch-unpack-transform/fetch-unpack-transform.py
- extension/CHANGELOG.md
- extension/README.md
- Update README and changelog.
- fetch-unpack-transform.py also exports transunit-id and targets.
> Changelog and README for 0.3.37

- extension/src/ALObject/ALObject.ts
Fixes #86  .
I think that the issue and code change says it all ;)
> Prevent XmlDocs before object declaration throws error #86

- .github/workflows/node.js.yml
- README.md
- extension/README.md
Added some pretty badges to README :)
Since the text for the "Run Tests" badge is based on the action name I'd like to change the name of the runner to "Tests" before we merge this one.
> Add badges to README.

- extension/frontend/XliffEditor/main.js
- extension/frontend/XliffEditor/reset.css
- extension/package-lock.json
- extension/src/XLIFFDocument.ts
- extension/src/XliffEditor/HTML.ts
- extension/src/XliffEditor/XliffEditorPanel.ts
Fixes #94  .
- Retain filter after panel update
- Retain position after panel update
- Reload XLF file when tab comes into focus.
> Xliff Editor - Now

- extension/src/ALObject/ALParser.ts
- extension/src/ALObject/Enums.ts
- extension/src/ALObject/Maps.ts
Adds support for new multi language properties.
AboutText and AboutTitle from #90 plus a few others that where missing...
> Added ML properties

- extension/src/ALObject/ALParser.ts
- extension/src/ALObject/Enums.ts
- test-app/Xliff-test/Translations/Al.g.xlf
- test-app/Xliff-test/src/TestPageExt.PageExt.al
- test-app/Xliff-test/src/TestTableExt.TableExt.al
> Fix "Caption changes in table/page extensions is not supported"

- extension/src/ALObject/ALObject.ts
- extension/src/ALObject/ALParser.ts
- extension/src/ALObject/Enums.ts
- extension/src/ALObject/Maps.ts
- extension/src/Documentation.ts
Fixes #90
Supports Report Extension that's available from BC18.
> Report Extension support

- extension/CHANGELOG.md
- extension/README.md
- extension/package.json
- extension/src/ALObject/ALControl.ts
- extension/src/ALObject/ALObject.ts
- extension/src/ALObject/ALParser.ts
- extension/src/ALObject/ALProcedure.ts
- extension/src/ALObject/ALTenantWebService.ts
- extension/src/ALObject/ALVariable.ts
- extension/src/ALObject/Enums.ts
- extension/src/ALObject/Maps.ts
- extension/src/Documentation.ts
- extension/src/Settings.ts
- extension/src/ToolTipsFunctions.ts
- extension/src/test/ALObjectTestLibrary.ts
- extension/src/test/ALParser.test.ts
Fixes #126.
- Optionally creates pages for Deprecated Features
- Based on objects/procedures/controls with ObsoleteState = Pending
> Deprecated Features

- extension/CHANGELOG.md
- extension/README.md
- extension/package.json
- extension/src/NABfunctions.ts
- extension/src/extension.ts
> Add Xml Comment formatting

- dev-tools/fetch-unpack-transform/requirements.txt
Just changing the requirements to use set version or newer.
> change required versions

- extension/CHANGELOG.md
- extension/README.md
- extension/delivery.json
- extension/package.json
- extension/src/ALObject/ALControl.ts
- extension/src/ALObject/ALObject.ts
- extension/src/ALObject/ALPageControl.ts
- extension/src/ALObject/ALPageField.ts
- extension/src/ALObject/ALPagePart.ts
- extension/src/ALObject/ALParser.ts
- extension/src/ALObject/ALProcedure.ts
- extension/src/ALObject/ALTableField.ts
- extension/src/ALObject/ALVariable.ts
- extension/src/ALObject/ALXmlComment.ts
- extension/src/Common.ts
- extension/src/Documentation.ts
- extension/src/Settings.ts
- extension/src/ToolTipsFunctions.ts
- extension/src/constants.ts
- extension/src/test/ALObjectTestLibrary.ts
- extension/src/test/ALParser.test.ts
- extension/src/test/ALXmlComment.test.ts
Fixes #147, Table Documentation.
- Documentation for tables, enabled by setting
- Docs for tableextension and pageextensions
- Fixes for paramrefs
- Yaml Header settings
- Adjustements of docs
> Table Documentation

- extension/.vscode/launch.json
- extension/.vscode/tasks.json
- extension/CHANGELOG.md
- extension/src/ALObject/ALCodeLine.ts
- extension/src/ALObject/ALParser.ts
- extension/src/ALObject/ALProcedure.ts
- extension/src/SymbolReference/BinaryReader.ts
- extension/src/SymbolReference/SymbolReferenceReader.ts
- extension/src/constants.ts
- extension/src/test/ALParser.test.ts
- extension/src/test/ToolTip.test.ts
- Improves the handling of pragma directives in code. 
- Improved parsing of procedures
> Improved handling of pragmas

- dev-tools/fetch-unpack-transform/fetch-unpack-transform.py
- extension/src/test/ExternalResources.test.ts
- "[*] New language: {lang_code}. Make sure to update affected files e.g BaseAppTranslationFiles.ts"
- Made some minor improvements/corrections. Mainly for "better" terminal output.
> Notify if new language occurs when parsing language files

- extension/frontend/XliffEditor/main.js
null errors crashes `frontend/main.js`
> null check on getElementById

- extension/src/LanguageFunctions.ts
- extension/src/NABfunctions.ts
- extension/src/externalresources/ExternalResources.ts
Fixes #172 .
- Ensure BaseApp JSON files are not empty before parsing.
- Throw some errors.
- Display better error messages to the user.
- Delete empty files if download fails.
Feel free to chime in on the error messages :D
> base app lang files

- extension/src/ALObject/ALParser.ts
- extension/src/ALObject/Enums.ts
- extension/src/ALObject/Maps.ts
- extension/src/test/ALObjectTestLibrary.ts
> PermissionSet object support

- extension/CHANGELOG.md
- extension/src/ALObject/ALParser.ts
- test-app/Xliff-test/src/TestXmlPort.XmlPort.al
Fixes #187.
- Add support for RequestPage Fields in XmlPorts
> Add support for RequestPage Fields in XmlPorts

- .github/workflows/node.js.yml
- extension/src/test/CliSettingsLoader.test.ts
- extension/src/test/ExternalResources.test.ts
- extension/src/test/HTML.test.ts
- extension/src/test/Version.test.ts
- test-app/Xliff-test/.gitignore
- test-app/Xliff-test/.vscode/launch.json
- Adding more tests! This gets us up to 77.45% :rofl: 
@jwikman when you find the time take a look at the changes in commit https://github.com/jwikman/nab-al-tools/pull/193/commits/1db89b412da378599729fd68d1bd85d3987abffe it appears we might have a difference in behavior depending on platform. I would not say this is critical but it would be nice to grasp the what or why :)
> We need more tests

- extension/src/ALObject/ALEnumValue.ts
- extension/src/ALObject/ALParser.ts
- extension/src/ALObject/Enums.ts
- extension/src/ALObject/Maps.ts
- extension/src/Documentation.ts
> Include extensible Enums in Ext. Doc.

- extension/src/Documentation.ts
> Controls group should not be printed if empty

- extension/src/ALObject/ALProcedure.ts
- extension/src/Documentation.ts
> Only print ServiceEnabled procedures on API docs

- extension/CHANGELOG.md
- extension/src/XlfHighlighter.ts
- extension/src/constants.ts
> Decorate the "NAB AL Tool Refresh Xlf" notes

- extension/src/Xliff/XLIFFDocument.ts
- extension/src/test/XLIFFTypes.test.ts
We agreed that the sort idea is dead right? Let's remove this. We'll probably rewrite this either way if it would ever be considered again.
> Remove unused sort function

- dev-tools/PowerShell/.gitignore
- dev-tools/PowerShell/library/Publish-ToMarketplace.ps1
- extension/CHANGELOG.md
- extension/README.md
- extension/package-lock.json
- extension/package.json
- extension/src/NABfunctions.ts
- extension/src/Settings/Settings.ts
- extension/src/Settings/SettingsMap.ts
- extension/src/Telemetry.ts
- extension/src/Xliff/XliffCache.ts
- extension/src/extension.ts
Fixes #238 .
- Logs usage of all functions triggered in NABFunctions.ts. Should be all functions that the user can invoke, right?
- Setting to allow disabling telemetry. Telemetry is enabled as default.
- Logs handled exceptions in NABFunctions.ts
- It _should_ handle unhandled exceptions, if I understand things properly... But I haven't seen anything in the logs yet.
> AppInsights Telemetry

- CODING_GUIDELINES.md
- CONTRIBUTING.md
Closes #98.
-  Add link and descriptive text to encourage improvement suggestions and requests based on best practices.
By no means does this mean that we are completly aligned with the guidelines. We have however not identified any major areas where we stray to far away from the guidelines.
> docs: add link to best practice guidelines

- .github/workflows/scripts/cli-test.ps1
- extension/.vscode/tasks.json
- test-app/.prettierignore
Fixes the last part of #257.
- The output of CreateDocumentation.js is compared against what's already in the TestApp repo
- Task to run the CLI tests locally
- Prettier shall not format files in the docs folder
> Test results from CLI CreateDocumentation.js

- extension/src/LanguageFunctions.ts
Fixes #261.
-  Write file synchronously :sunglasses:
> fix(languagefunctions): write file synchronously

- .github/workflows/node.js.yml
Run workflow on node 14.x and 16.x
> run on node 14.x and 16.x

- extension/src/ALObject/ALElementTypes.ts
- extension/src/ALObject/ALParser.ts
- extension/src/ALObject/Enums.ts
- extension/src/constants.ts
- extension/src/test/ALObject/ALObject.test.ts
- extension/src/test/ALObjectTestLibrary.ts
- test-app/Xliff-test/Translations/Al.g.xlf
- test-app/Xliff-test/src/TestReport.Report.al
Fixes #319 .
- Added support for Report Labels
- Added tests
- Added Report Labels to TestApp
> fix: Support for Report Labels

- extension/src/ALObject/ALElementTypes.ts
- Casing on the object type in the permissionset was wrong. It should be lowercase...
> Casing on object type in permission set

- extension/CHANGELOG.md
- extension/src/ALObject/ALParser.ts
- extension/src/ALObject/Enums.ts
- extension/src/ALObject/Maps.ts
- extension/src/test/ALObjectTestLibrary.ts
- extension/src/test/ALParser.test.ts
Fixes #330.
- Support for PermissionSet Extension. Don't ask me why this was not added at the same time as the PermissionSet object...
> feat: Support for PermissionSet Extension #330

- extension/CHANGELOG.md
- extension/src/PermissionSet/PermissionSetFunctions.ts
- extension/src/WorkspaceFunctions.ts
- extension/src/test/PermissionSet.test.ts
- extension/src/test/resources/permissionset/permissionSet.xml
- extension/src/test/resources/permissionset/permissionSet2.xml
- The functionality around XML PermissionSets did fail if the permissionset was using namespaces. This should now be fixed
- A test for XML PermissionSets
> fix: Improved handling of XML PermissionSets

- .github/workflows/publish.yml
- dev-tools/PowerShell/library/Create-VSIX-Workflow.ps1
- dev-tools/PowerShell/library/Create-VSIX.ps1
- extension/package-lock.json
- extension/package.json
> ci: Release workflow

- extension/.nycrc.json
- extension/src/test/CSV.test.ts
- extension/src/test/resources/xlf-update-target-state.csv
- extension/src/test/resources/xlf_export-semi-colon.csv
Closes #373 .
- Improved testing of branches and errors
> Improved test of CSV branches

- extension/CHANGELOG.md
- extension/src/Documentation.ts
- extension/src/Settings/Settings.ts
- Added some more metadata from `app.json` to the `info.json` generated by `NAB: Generate External Documentation`
> feat(Docs): Added app metadata to info.json

- extension/CHANGELOG.md
- extension/src/PermissionSet/PermissionSetNamePanel.ts
- extension/src/Template/TemplatePanel.ts
Related to #382 .
- Keep states in Webviews
> fix: Keep state in Webviews

- extension/CHANGELOG.md
- extension/src/Error.ts
- extension/src/NABfunctions.ts
- extension/src/XlfHighlighter.ts
- extension/src/Xliff/XLIFFDocument.ts
- extension/src/test/ALObjectTestLibrary.ts
- extension/src/test/Documentation.test.ts
- extension/src/test/LanguageFunctions.test.ts
- extension/src/test/TaskRunner.test.ts
Related to #395 .
- Throw an error if a trans-unit has another trans-unit as child
- Highlight above
> feat: Handle trans-units inside trans-units

- extension/snippets/misc.json
I don't think this needs any further explanation 😜
Reported to our info mail...
> fix: Spelling Dictonary -> Dictionary

- extension/.nycrc.json
- extension/package.json
- extension/src/ALObject/ALElementTypes.ts
- extension/src/Settings/Settings.ts
- extension/src/Settings/SettingsMap.ts
- extension/src/WorkspaceFunctions.ts
- extension/src/XliffFunctions.ts
- extension/src/cli/RefreshXLF.ts
- extension/src/test/ALObject/ALObject.test.ts
- extension/src/test/LanguageFunctions.test.ts
- extension/src/test/XlfHighlighter.test.ts
- extension/src/test/bugs/333.test.ts
- nab-al-tools.code-workspace
Preview implementation of "translations from comments"
> feat: LanguageCodesInComments

- .github/workflows/nerd-stuff.yml
- .github/workflows/publish.yml
- extension/CHANGELOG.md
- extension/src/ALObject/ALDataType.ts
- extension/src/ALObject/Enums.ts
- extension/src/ALObject/RegexPatterns.ts
- extension/src/ToolTipsDocumentation.ts
- extension/src/test/ALParser.test.ts
- extension/src/test/Settings/CliSettingsLoader.test.ts
- Added support for ToolTip in Labels
- Added support for ControlAddIn
- Added support for namespace
> feat: Support for namespace, ControlAddIn and ToolTips in Labels

- extension/CHANGELOG.md
- extension/src/ALObject/ALPageField.ts
- test-app/Xliff-test/Translations/Al.g.xlf
- test-app/Xliff-test/docs/info.json
- test-app/Xliff-test/src/ToolTip/ToolTip.Table.al
- test-app/Xliff-test/src/ToolTip/ToolTipPart2.Page.al
- test-app/Xliff-test/src/ToolTip/ToolTips.Page.al
> feat: Support for ToolTips on table fields #460

- extension/src/Error.ts
- extension/src/NABfunctions.ts
- extension/src/Settings/CliSettingsLoader.ts
- extension/src/Telemetry/Telemetry.ts
- extension/src/WorkspaceFunctions.ts
This pull request introduces a new error class, `ApplicationManifestError`, and integrates it into various parts of the codebase. Additionally, it includes improvements to the telemetry logging mechanism.
* Added `ApplicationManifestError` class to handle cases where the `app.json` file is missing or invalid.
* Updated `NABfunctions.ts` to import and handle `ApplicationManifestError` alongside other errors. [[1]](diffhunk://#diff-e3e8c3f0c1f92cc39eb312eac6568fc9e1b3553d3702e4354eed24cafbb1b48fR34) [[2]](diffhunk://#diff-e3e8c3f0c1f92cc39eb312eac6568fc9e1b3553d3702e4354eed24cafbb1b48fL1297-R1301)
* Modified `CliSettingsLoader.ts` to throw `ApplicationManifestError` if the `app.json` file is missing or invalid. [[1]](diffhunk://#diff-53f4c06deaa78c8ee22c319e5773722cd083803e0deaa16c596ee98891 …
> fix: Improve error and telemetry handling

- extension/.nycrc.json
- extension/CHANGELOG.md
- extension/README.md
- extension/package-lock.json
- extension/package.json
- extension/src/CSV/ExportXliffCSV.ts
- extension/src/ChatTools/GetTextsToTranslateTool.ts
- extension/src/ChatTools/GetTranslatedTextsToReviewTool.ts
- extension/src/ChatTools/RefreshXlfTool.ts
- extension/src/ChatTools/SaveTranslatedTextsTool.ts
- extension/src/NABfunctions.ts
- extension/src/RefreshResult.ts
- extension/src/Settings/LanguageFunctionsSettings.ts
- extension/src/Xliff/XLIFFDocument.ts
- extension/src/XliffEditor/XliffEditorPanel.ts
- extension/src/XliffFunctions.ts
- extension/src/extension.ts
- extension/src/test/ChatTools/GetTextsToTranslateTool.test.ts
- extension/src/test/ChatTools/GetTranslatedTextsToReviewTool.test.ts
- extension/src/test/ChatTools/SaveTranslatedTextsTool.test.ts
- extension/src/test/LanguageFunctions.test.ts
- Introduce new features for managing translation states and retrieving texts needing review. 
- Improve feedback messages for translation processes.
> Enhance translation tools with state management and improved reporting
