jwikman/nab-al-tools

- README.md
- package.json
- src/LanguageFunctions.ts
- src/NABfunctions.ts
- src/Settings.ts
- src/VSCodeFunctions.ts
- src/XlfFunctions.ts
> Use state property in xlf-files #17

- CHANGELOG.md
- README.md
- package.json
- src/LanguageFunctions.ts
- src/Settings.ts
Fixes #9 
New setting NAB.MatchTranslation
- If enabled, the "NAB: Refresh XLF files from g.xlf" function tries to match sources in the translated xlf file to reuse translations. A found match of "source" is then prefixed with [NAB: REVIEW] for manual review. If several matches are found, all matches are added and you need delete the ones you do not want. You can do this by using "Find next untranslated" (Ctrl+Alt+U). This feature only works if "UseExternalTranslationTool" is disabled.
> MatchTranslation

- extension/CHANGELOG.md
- extension/README.md
- extension/src/ALObject.ts
- extension/src/Common.ts
- extension/src/LanguageFunctions.ts
- extension/src/NABfunctions.ts
- extension/src/VSCodeFunctions.ts
- extension/src/WorkspaceFunctions.ts
- extension/src/XLIFFDocument.ts
- extension/src/XmlFormatter.ts
- extension/src/test/ALObjectTestLibrary.ts
- extension/src/test/AlFunctions.test.ts
- extension/src/test/LanguageFunctions.test.ts
- extension/src/test/XLIFFTypes.test.ts
- extension/src/test/XmlFormatter.test.ts
- test-app/Xliff-test/Translations/Al.g.xlf
- test-app/Xliff-test/src/TestReport.Report.al
- test-app/Xliff-test/src/TestXmlPort.XmlPort.al
- Handles issue where "<source> </source>" got replaced with "<source></source>"
- Handle captions on obsolete objects
> Keep spaces in source/target

- extension/package-lock.json
- extension/src/test/BaseAppTranslationFiles.test.ts
- extension/src/test/ExternalResources.test.ts
Some tests are slow and may be unnecessary to run every time locally. Hopefully this little check & skip will speed things up. It also marks the tests as pending so that you know they didn't run. This is achieved by checking for a GitHub environment variable like this:
```TypeScript
if (!process.env.GITHUB_ACTION) {
this.skip();
}
``` 
`GITHUB_ACTION` is an environment variable set by GitHub when creating the containers. [More info here](https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables)
This is how it should look like when running locally. 
The pending test should run in the GitHub workflow. At this point all tests should run in the GitHub workflow. As seen in the test runs for this PR.
> Skipping slow tests locally

- CONTRIBUTING.md
- extension/CHANGELOG.md
- extension/src/LanguageFunctions.ts
- extension/src/test/ALObjectTestLibrary.ts
- extension/src/test/LanguageFunctions.test.ts
Fixes #120.
- New search function that searches for multiple targets.
- The closest of the findings is used as result and presented to the user.
- A small refactor to allow testing of search functions
- Added tests for search functions
It's good enough but I'm not completely convinced my regex approach is the best way. I'd tried to get some grouping going so that it would be possible to mark the multiple targets line by line but my regex skills weren't enough. I'd love some input if you get any ideas :)
> Find next untranslated - Stop at multiple targets

- extension/CHANGELOG.md
- extension/README.md
- extension/frontend/XliffEditor/main.js
- extension/frontend/XliffEditor/reset.css
- extension/src/XLIFFDocument.ts
- extension/src/XliffEditor/HTML.ts
- extension/src/XliffEditor/XliffEditorPanel.ts
- extension/src/test/ExternalResources.test.ts
- extension/src/test/XLIFFTypes.test.ts
- extension/src/test/XliffEditor.test.ts
Fixes #13 
- Filter and display transunits with matching source and different translations.
- Move focus with arrow up / down.
- copy value with `F8`
Adds new properties to class `TransUnit` that returns value from `Target[0]` or empty string if null or undefined.
- `targetTextContent`
- `targetState`
- `targetTranslationToken`
> Identify differently translated

- extension/CHANGELOG.md
- extension/README.md
- extension/src/PowerShellFunctions.ts
- extension/src/Settings.ts
Fixes #131 with a new setting, `NAB.SigningTimeStampServer`.
Changes default TimeStamp server to http://timestamp.digicert.com
> #131 Setting for TimeStampServer

- extension/CHANGELOG.md
- extension/README.md
- extension/package.json
- extension/src/CSV/CSV.ts
- extension/src/CSV/ExportXliffCSV.ts
- extension/src/CSV/ImportXliffCSV.ts
- extension/src/LanguageFunctions.ts
- extension/src/NABfunctions.ts
- extension/src/Settings.ts
- extension/src/XLIFFDocument.ts
- extension/src/XlfFunctions.ts
- extension/src/XliffEditor/XliffEditorPanel.ts
- extension/src/test/CSV.test.ts
- extension/src/test/LanguageFunctions.test.ts
- extension/src/test/XLIFFTypes.test.ts
- Support for xlf files from Dynamics LCS (removes empty dev notes)
- Shows Target State (and State Qualifier) in the Xliff Editor, if "Use External Translation Tool" is enabled.
- Added a default `target` property on TransUnit, instead of using `targets[0]` everywhere
- Added a setting to let the user configure how Target State should be handled when importing from .csv file
> Dynamics LCS support

- extension/src/NABfunctions.ts
Hello,
When try to use use function findTranslatedTexts from some *.al file in Base Applicaiton, then it fails with breaking error "Files above 50MB cannot be synchronized with extensions."
This PR changes behavior. If unable to open TextEditor, then only open Search with search string "Page ... - Property ..."...
BR
zabaq
> findTranslatedTexts - Large Target File Fix

- extension/CHANGELOG.md
- extension/src/NABfunctions.ts
Fixes #162.
- After the new xlf is created via `NAB: Create translation XLF for new language`, the `NAB: Refresh XLF files from g.xlf` function is executed on the new file
- This adds target elements to all trans-units
> Execute "Refresh Xlf" after a new xlf is created

- extension/package-lock.json
- extension/package.json
- extension/src/Settings.ts
Require breaks functionality and the first implementation didn't support reading utf8 with bom which app.json is encoded as.
> Support reading app.json and launch.json as utf8 with bom

- extension/frontend/XliffEditor/reset.css
Fixes #176  .
- Use colors from current theme in css. 
Looks good in all themes (4) that I've tried :)
> use theme colors for Xliff Editor

- extension/src/CSV/ExportXliffCSV.ts
- extension/src/Xliff/XLIFFDocument.ts
- extension/src/test/XLIFFTypes.test.ts
Fixes #181
- Change return type of `Xliff.xliffGeneratorNote()` to `Note | undefined`. Since the function filters the notes array and returns the item at index 0 it could possibly turn up `undefined`. I'm a bit disappointed that the compiler isn't warning for this already(?!).
- Throw error `Could not find a note from "Xliff Generator" in trans-unit "xxx"` in `Xliff.getXliffIdTokenArray()` if the note is `undefined` 
- Cleaned up some bits and pieces as I passed by :)
There's no bugs in this repository, only missing test cases ;)
> Change return type of function Xliff.xliffGeneratorNote()

- extension/CHANGELOG.md
- extension/src/LanguageFunctions.ts
- extension/src/Xliff/XLIFFDocument.ts
- extension/src/test/LanguageFunctions.test.ts
- extension/src/test/XLIFFTypes.test.ts
Fixes #179  .
- Add a note if source only contains whitespaces in an untranslated trans-unit 
- Some clean up of deprecated functions
I had actually forgotten about this branch so it feels a bit like sleepwalking when making this PR. So hit me with your best shot, it might make me wake up :D
> Detect whitespace sources

- dev-tools/fetch-unpack-transform/fetch-unpack-transform.py
- extension/CHANGELOG.md
- extension/src/LanguageFunctions.ts
- extension/src/NABfunctions.ts
- extension/src/externalresources/ExternalResources.ts
- extension/src/test/BaseAppTranslationFiles.test.ts
- extension/src/test/ExternalResources.test.ts
Mitigates parts of the problem in #190  .
- More informative message when parsing of translation maps fail.
- `NAB: Download Base App Translation Files` now shows number of succeded / failed downloads
- Changed return signature of `BlobContainer.getBlobs` to return an object `{  succeded: 0, failed: 0 }` represented by new interface `BlobDownloadResult`.
- After translation maps are downloaded we try parsing them, if parsing fails the file is deleted.
This isn't the solution to the core problem with partial downloads but it will mitigate some of the issues and make for a less disruptive experience for the user. 
Tried another way of parsing the xliffs from Base App without success. I think this is as fast as it gets with Python …
> base app translation map validation

- extension/CHANGELOG.md
- extension/src/Documentation.ts
Adds the app name to the info.json created when generating external documentation. This can be useful as metadata for DocFx or other engines that transforms the md files to html.
> Added "app-name" to info.json

- extension/src/Common.ts
- extension/src/DocumentFunctions.ts
- extension/src/Documentation.ts
- extension/src/LanguageFunctions.ts
- extension/src/VSCodeFunctions.ts
- extension/src/test/CliSettingsLoader.test.ts
- extension/src/test/Common.test.ts
- extension/src/test/DocumentFunctions.test.ts
- extension/src/test/LanguageFunctions.test.ts
- extension/src/test/VSCodeFunctions.test.ts
This brings us to 79.3%! It's a slow process to say the least. A good thing with using code coverage is that it shows code paths not taken like `if/else` which reveals a lot of small missed test cases. 
- Refactor formatToday -> formatDate. Not that we have any use for it, but it made for a better test case. Plus it's a more useful function now... I guess :)
- Removed function `DocumentFunctions.searchTextFile()`. I could not see that it was in use, it's not a hard function to re-create, we use other functions for those purposes.
- Removed function `DocumentFunctions.documentLineEnding()` it felt superfluous, replaced with existing function `eolToLineEnding`
- Removed version conditional in `VSCodeFunctions.findTextInFiles`. VS Code 1.34.0 was …
> Adding more tests

- extension/src/NABfunctions.ts
- extension/src/Settings/Settings.ts
- extension/src/WorkspaceFunctions.ts
- Delete `WorkspaceFunctions.getTranslationFolderPath`
- Replace with `Settings.translationFolderPath`
- Delete `WorkspaceFunctions.getDtsWorkFolderPath`
- Replace with `Settings.dtsWorkFolderPath`
> Refactor functions to getters on Settings

- extension/src/ALObject/ALParser.ts
- extension/src/test/ALObjectTestLibrary.ts
- extension/src/test/ALParser.test.ts
Retake of #210 
Using the word matching from AL Language extension to match object names. That made it possible to remove some error handling.
Tests improved to test the additions
Known limitations:
Does _not_ handle /* comments, only // comments
> Improved parsing of object names

- extension/src/test/BaseAppTranslationFiles.test.ts
- extension/src/test/DocumentFunctions.test.ts
- extension/src/test/ExternalResources.test.ts
- extension/src/test/XlfHighlighter.test.ts
Asserting rejected promises in asynchronous functions is no longer a mystery!
I started out hunting that path/file error but soon realized there was more to find. I fixed the most obvious cases but there might be more. From the experiences I've had while learning how `assert.rejects` works. I would say that there's a high risk for false positives when testing asynchronous functions. 
There are still some unexplained crap lines being outputted in the workflow. We'll have to keep an eye out for those.
Are we ready to activate squash merge again?
> Handle rejected promise in test

- extension/src/DocumentFunctions.ts
- extension/src/test/DocumentFunctions.test.ts
- test-app/Xliff-test/Translations/Al.g.xlf
- test-app/Xliff-test/src/Empty.Table.al
Fixes #218 .
Hi @jwikman, @theschitz . 
I hope this is my last time where I'm going to interrupt you, so sorry for all the PRs and for keeping you busy with all my wishes :)
My change as such is described in the issue linked above.
Let me explain a bit the changes I made:
- The change in the .xlf seems to be a big one, but actually I just added the Empty.Table.al and built the project, so that the Caption of the Field is showing up (see [here](https://github.com/jwikman/nab-al-tools/compare/master...DavidFeldhoff:master#diff-de075a73e2a36ead8f95fc7f94934122a914e02e922902f344a50772e77b7013R9))
- The real change is made [here](https://github.com/jwikman/nab-al-tools/compare/master...DavidFeldhoff:master#diff-98e93b82acc20d494754543d188a59cc931ea277759cc125abb2e08d2a572354R92) where I try to …
> Try to find parent (field/table/..) if property is missing

- extension/package-lock.json
- extension/package.json
- extension/src/externalresources/ExternalResources.ts
- extension/src/test/CliSettingsLoader.test.ts
- extension/src/test/ExternalResources.test.ts
- Replacing `Axios` with `https`. 
The code doesn't really look that much different but there's some value in stripping away the "magic" of Axios. I think working with `https` will prove to be more natural and better suited for our use case. 
[HTTPS | Node.js v17.2.0 documentation](https://nodejs.org/api/https.html#httpsgeturl-options-callback)
Apparently `follow-redirects` was also removed when uninstalling `Axios` :+1:
> Replace Axios with https

- extension/CHANGELOG.md
- extension/delivery.json
- extension/package-lock.json
- extension/package.json
- extension/src/ALObject/ALParser.ts
- extension/src/ALObject/Enums.ts
- extension/src/test/ALObjectTestLibrary.ts
- extension/src/test/ALParser.test.ts
- test-app/Xliff-test/Translations/Al.g.xlf
- test-app/Xliff-test/app.json
- test-app/Xliff-test/src/TestReportExt.ReportExt.al
Fixes #221 "Bug on ReportExtension Objects"
Adds support for modified report columns.
> Support Report Extension modification

- extension/src/Enums.ts
- extension/src/LanguageFunctions.ts
- extension/src/NABfunctions.ts
- extension/src/RefreshResult.ts
- extension/src/Settings/LanguageFunctionsSettings.ts
- extension/src/XliffEditor/XliffEditorPanel.ts
- extension/src/test/LanguageFunctions.test.ts
- extension/src/test/XlfHighlighter.test.ts
I was looking into #158  and realized that it would require some refactoring to avoid `vscode` and circular dependencies. It felt wiser to do the refactoring as a separate step.
- Move exported enums to `src/Enums.ts`
- I looked at the option of creating them as separate files but collecting them makes for a slimmer import statement. I did only move exported enums from `LanguageFunctions.ts` since it's a general purpose file and most other enums are already placed where they "belong".
- Move `LanguageFunctionsSettings` to own file.
- Move `RefreshResult` to own file.
- refactored `isChanged` as a getter.
- Only references updated in tests.
> Refactor exported classes and enums of LanguageFunctions

- extension/src/LanguageFunctions.ts
- extension/src/NABfunctions.ts
- extension/src/Xliff/XLIFFDocument.ts
- extension/src/test/LanguageFunctions.test.ts
- extension/src/test/VSCodeFunctions.test.ts
- extension/src/test/XLIFFTypes.test.ts
Maybe not as well motivated as the previous PR. This does however add test for previously untested functions and removes a bit of old code :)
- Refactor functions `findAllUnTranslatedText` and `findMultipleTargets` of `NABFunctions.ts`
- Refactor the called functions of `LanguageFunctions.ts` to return the search parameters. This makes for more testable code :+1: 
- Move async call to `vscode` api up one step in hierarchy `NABFunctions.ts`
- Add tests 
- Refactor generation of trans-unit target state search strings
- Remove superfluous function `targetStateActionNeededToken`
- apply skills learned since orginal creation
- added tests
> Refactor target state function

- extension/package.json
- extension/src/DocumentFunctions.ts
- extension/src/LanguageFunctions.ts
- extension/src/NABfunctions.ts
- extension/src/Types.ts
- extension/src/extension.ts
- extension/src/test/DocumentFunctions.test.ts
- extension/src/test/LanguageFunctions.test.ts
- Add new type `TextDocumentMatch`.
- Have `LanguageFunctions.findNextUnTranslatedText` and `LanguageFunctions.revealTransUnitTarget` return undefined or result as `TextDocumentMatch`.
- The functions are now somewhat testable.
- `revealTransUnitTarget` had a condition that it would only run if there only was one target translation. This has now been removed and the signature refactored to only take a single file path and a translation unit id as parameters.
- Move call to `DocumentFunctions.openTextFileWithSelection` up the hierarchy. I think this allows for better control, clearer purpose and definition of the functions involved.
- Break dependency on `DocumentFunctions.ts` by cloning `eolToLineEnding`. Mainly because I knew it was the last …
> Refactor return typed result from search functions

- extension/package-lock.json
- extension/package.json
- extension/src/LanguageFunctions.ts
- extension/src/XlfHighlighter.ts
- extension/src/Xliff/XLIFFDocument.ts
- extension/src/constants.ts
- extension/src/test/XlfHighlighter.test.ts
- Remove and uninstall dependency on `escape-string-regexp`. It was only used in one occurence.
- There is a slight difference in how [escape-string-regexp](https://github.com/sindresorhus/escape-string-regexp/blob/main/index.js) works and our own `Common.escapeRegexp` works. If it's of critical importance we should implement the same.
- RegEx constant `translationTokenSearchExpression` moved from `Common` to `XliffDocument` this leaves Common without imports from internal libraries :+1:
> refactor: move xliff constants

- extension/src/Common.ts
- extension/src/Documentation.ts
- extension/src/FileFunctions.ts
- extension/src/LanguageFunctions.ts
- extension/src/NABfunctions.ts
- extension/src/test/Common.test.ts
- extension/src/test/FileFunctions.test.ts
- extension/src/test/LanguageFunctions.test.ts
Passing settings and app manifest to `zipXlfFiles` just to get the xlf files seemed superfluous so I made it more generic.
- `zipXlfFiles` is now refactored be the more generic `zipFiles`. 
- `mkDirByPathSync`, `deleteFolderRecursive` and `createFolderIfNotExist` moved from `Common.ts` to `FileFunctions.ts`
> refactor: zipXlfFiles becomes zipFiles in FileFunctions

- extension/package.json
- extension/src/ALObject/ALParser.ts
- extension/src/LanguageFunctions.ts
- extension/src/NABfunctions.ts
- extension/src/Settings/Settings.ts
- extension/src/Settings/SettingsMap.ts
- extension/src/Types.ts
- extension/src/Xliff/XliffCache.ts
- extension/src/extension.ts
- extension/src/test/ALObjectTestLibrary.ts
Fixes #231.
- Show translations on hover, with link to the translation unit in the xlf file
- A setting to disable this feature, it can be slow with BIG XLF files, EnableTranslationsOnHover
- Caching of XLF files. Enabled by above setting. 
- Fixed a few regex matching that were case sensitive, it couldn't parse the base-app..
The caching might be useful for other XLIFF functions as well...
Tests are still missing, but don't know if we need to do them until we polished the hover texts a bit more...
> Hover for translations

- extension/package.json
- extension/syntaxes/dtsDictionarySyntax.json
Fixes #237  .
- Adds schema for DTS dictionary.
Went with the enum for language code, it's either that or regex. Enum felt more helpful to the user and could give us a heads up if we're missing a base app translation map.
> Add schema for dictionary

- extension/CHANGELOG.md
- extension/README.md
- extension/frontend/PermissionSetNameEditor/main.css
- extension/frontend/PermissionSetNameEditor/main.js
- extension/frontend/PermissionSetNameEditor/reset.css
- extension/frontend/PermissionSetNameEditor/vscode.css
- extension/package-lock.json
- extension/package.json
- extension/src/ALObject/ALElementTypes.ts
- extension/src/ALObject/Enums.ts
- extension/src/ALObject/Maps.ts
- extension/src/NABfunctions.ts
- extension/src/PermissionSet/PermissionSetFunctions.ts
- extension/src/PermissionSet/PermissionSetNamePanel.ts
- extension/src/PermissionSet/XmlPermissionSet.ts
- extension/src/Settings/CliSettingsLoader.ts
- extension/src/Settings/Settings.ts
- extension/src/Settings/SettingsLoader.ts
- extension/src/WorkspaceFunctions.ts
- extension/src/extension.ts
Ref. https://www.yammer.com/dynamicsnavdev/threads/1186383901990912
- Prompts user for prefix, with default value from AppSourceCop.json
- Shows a table where user can edit names and captions
- Input is validated
- New PermissionSet objects are created
- Old XmlPermissionSets are deleted
- An upgrade codeunit is created that maps usage of old PermissionSet to the new one.
> feat: Convert Xml PermissionSet to PermissionSet objects

- dev-tools/PowerShell/Get-LatestNABALTools.ps1
- extension/CHANGELOG.md
- extension/README.md
- extension/package.json
- extension/src/LanguageFunctions.ts
- extension/src/NABfunctions.ts
- extension/src/extension.ts
- extension/src/externalresources/ExternalResources.ts
- extension/src/test/BaseAppTranslationFiles.test.ts
- extension/src/test/ExternalResources.test.ts
Fixes #243.
- Copies the content of the <source> element to the <target> element for all translation units that is untranslated. All copied targets are optionally marked for review.
Sorry about the unrelated diffs in the changelog. I activated prettier for .md files for a while, but the readme became a complete diff so I reverted that. But I missed that the changelog already was affected.
I'll activate prettier for .md and .js files in another PR after this is completed.
> Copy all <source> to untranslated <target>

- extension/src/ALObject/ALElementTypes.ts
- extension/src/ALObject/ALParser.ts
- extension/src/test/ALParser.test.ts
- extension/src/test/AlFunctions.test.ts
Fixes #248.
- Replace "double double quotes" in control names
- Added tests for parsing control names
> Double quotes in control names

- extension/src/Xliff/XLIFFDocument.ts
- extension/src/XliffFunctions.ts
- extension/src/test/XLIFFTypes.test.ts
- extension/src/test/XliffFunctions.test.ts
- nab-al-tools.code-workspace
Closes #252.
- Move `setTargetStateFromToken` to `TransUnit` class.
- Add tests for `formatTransUnitForTranslationMode` and `setTargetStateFromToken`. Some of the tests for `formatTransUnitForTranslationMode` are overlapping. It felt better to include the overlap (as an integration test perhaps :wink: )  since there still is a separation of logic.
Was a bit tired writing this up so any smart ideas I'll take into consideration :sweat_smile:
> Refactor: Set TargetState from token

- extension/src/NABfunctions.ts
- Replace duplicated older function `getRefreshXlfMessage` with newer `RefreshResult.getReport()`
> refactor: replace getRefreshXlfMessage with RefreshResult.getReport()

- extension/.vscode/launch.json
- extension/src/Telemetry.ts
Fixes #266 .
- Disable telemetry if running in workflow
- Adds configuration "All Automatic Tests" in `launch.json` to enable running workflow tests locally.
> ci(telemetry): disable telemetry if running in workflow

- .github/workflows/node.js.yml
- extension/.vscode/launch.json
- extension/src/Telemetry.ts
- extension/src/test/suite/index-coverage.ts
- extension/src/test/suite/index.ts
Continuation of #266. As I went to bed last night I realized that I had merged to soon.
- Adds new env variable `NAB_DISABLE_TELEMETRY` to toggle telemetry independently.
- Disables telemetry in `launch.json` when running "Automatic Tests". This is very much up for discussion.
- Adds a smal log in `test/suite/index.ts` and `test/suite/index-coverage.ts` to confirm env var is set.
> ci(telemetry): add new env variable for telemetry

- .github/workflows/scripts/cli-test.ps1
- extension/.nycrc.json
- extension/package.json
- extension/src/ALObject/ALElementTypes.ts
- extension/src/Common.ts
- extension/src/Logging/ConsoleLogger.ts
- extension/src/Logging/ILogger.ts
- extension/src/Logging/NullLogger.ts
- extension/src/Logging/OutputLogger.ts
- extension/src/NABfunctions.ts
- extension/src/Settings/Settings.ts
- extension/src/Settings/SettingsMap.ts
- extension/src/extension.ts
- extension/src/test/Common.test.ts
- Adds a new setting, `NAB.EnableTroubleshootingCommands`, to enable Troubleshooting commands 
- Adds two new commands:
- NAB: Troubleshoot - Parse current file
- NAB: Troubleshoot - Parse current project
- The above commands tries to parse files as ALObjects.
- If successful, the object(s) is serialized to json and opened in a new TextEditor.
- Some properties are cleared to avoid circular reference in json
- Code lines are only output once per object
- Properties in json are sorted by name
- Improves the cli test when running locally
> feat: Troubleshooting commands

- extension/src/FileFunctions.ts
- extension/src/SymbolReference/SymbolReferenceCache.ts
- extension/src/SymbolReference/SymbolReferenceReader.ts
- extension/src/SymbolReference/types/AppPackage.ts
- extension/src/WorkspaceFunctions.ts
- extension/src/test/FileFunctions.test.ts
- extension/src/test/SymbolReference/AppPackage.test.ts
- extension/src/test/SymbolReference/SymbolReferenceCache.test.ts
- extension/src/test/Symbols.test.ts
Changes proposed in this PR:
- Move functions to more context appropriate files:
- `getZipEntryContentOrEmpty` from `SymbolReferenceReader` to `FileFunctions`. 
- Separate AppPackage functions from `SymbolReferenceReader` by moving them to `AppPackage` class with the intention to make `AppPackage` more self sufficient and stand alone.
- Added tests for `AppPackage`.
- Added two new interfaces: `AppFileContent` and `AppIdentifier`
- New class `SymbolReferenceCache`that follows the same pattern as `XliffCache`.
There still is a possibility to extract all functions except  `getObjectsFromAppFile` from `SymbolReferenceReader.ts` but I couldn't decide if that would be appropriate. The remaining functions feel like they're placed within the right context. 
`tableToObject` …
> refactor: symbol reference reader / cache

- extension/.vscode/launch.json
- Disables extensions when launching test from vscode. Should clean up some log clutter and hopefully speed some things up a bit.
> build: disable extensions when running tests in vscode

- dev-tools/test-coverage/README.md
- extension/.nycrc.json
- extension/src/test/VSCodeFunctions.test.ts
- extension/src/test/XliffFunctions.test.ts
- extension/src/test/markdown/YamlItem.test.ts
- extension/src/test/runTest-coverage.ts
- extension/src/test/suite/index-coverage.ts
- extension/src/test/suite/index.ts
- use `insiders` when running tests with `runTest-coverage.ts` this enables running command line tests without closing all instances of vscode! A [tip](https://code.visualstudio.com/api/working-with-extensions/testing-extension#tips) I just happened to stumble upon. I haven't noticed any issues running with insiders but it's important to note that this means that `insiders` will always be used in the workflow. It should be fine and it's simple to revert.
- I removed the reporters from NYC configuration. Duplicate reports were exported and only on of them were correct. The new README points you in the right direction.
- Removed some console logs that seemed out of place in the test runners.
- Added to tests to confirm that the coverage report was …
> ci: cli tests and coverage

- extension/CHANGELOG.md
- extension/README.md
- extension/package.json
- extension/src/ALObject/ALParser.ts
- extension/src/NABfunctions.ts
- extension/src/RenumberObjects.ts
- extension/src/Template/TemplateFunctions.ts
- extension/src/Template/TemplateTypes.ts
- extension/src/extension.ts
- extension/src/test/ALObject/ALObject.test.ts
- extension/src/test/DTSImport.test.ts
- extension/src/test/LanguageFunctions.test.ts
- extension/src/test/Template.test.ts
- extension/src/test/resources/templateSettings/al.template.json
- extension/src/test/resources/templateSettings/files/App/src/file3.al
- extension/src/test/resources/templateSettings/files/App/src/file4.al
- extension/src/test/resources/templateSettings/files/al.template.json
- extension/syntaxes/templateSettingsSyntax.json
Fixes one of the remaining items in #275.
- Support of renumbering AL Objects after Template is applied with a new setting, `renumberObjects` (default active)
- New feature: `NAB: Renumber AL objects`
- Moved some test code with file operations inside the suite. I believe that unnecessary things has been running when only one test is run. 
- Changed a Template setting, `removeSpaces` is now `replaceSpaces` and a new setting `replaceSpacesWith` specifies what the spaces should be replaced with
> feat: Renumber AL Objects

- extension/CHANGELOG.md
- extension/src/Documentation.ts
- test-app/Xliff-test/src/RemovedTable.Table.al
- test-app/Xliff-test/src/TestTable.Table.al
Fixes #286.
- Tables and Table Fields with ObsoleteState = Removed should not be included in the external documentation
> fix: ObsoleteState Removed removed from docs

- extension/.vscode/launch.json
- extension/CHANGELOG.md
- extension/src/ALObject/ALElementTypes.ts
- extension/src/ALObject/ALParser.ts
- extension/src/ALObject/Enums.ts
- test-app/TestApp.code-workspace
- test-app/Xliff-test/README.md
- test-app/Xliff-test/ToolTips.md
- test-app/Xliff-test/Translations/Al.g.xlf
- test-app/Xliff-test/docs/TOC.yml
- test-app/Xliff-test/docs/info.json
- test-app/Xliff-test/docs/page-nab-test-view/TOC.yml
- test-app/Xliff-test/docs/page-nab-test-view/index.md
- test-app/Xliff-test/docs/page-nab-test-view/test-method-page.md
- test-app/Xliff-test/docs/pages.md
- test-app/Xliff-test/docs/public-objects.md
- test-app/Xliff-test/docs/table-nab-test-table/index.md
- test-app/Xliff-test/src/RemovedTable.Table.al
- test-app/Xliff-test/src/TestPageExt.PageExt.al
- test-app/Xliff-test/src/TestReport.Report.al
- test-app/Xliff-test/src/TestReportExt.ReportExt.al
- test-app/Xliff-test/src/TestTable.Page.al
- test-app/Xliff-test/src/TestTable.Table.al
- test-app/Xliff-test/src/TestTableExt.TableExt.al
- test-app/Xliff-test/src/TestView.Page.al
Fixes parts of #288, where the command stops due to unexpected `modify`.
- Implemented support for Views in Pages and Page Extensions
- More info on Views: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-page-object#views
- Re-enabled other extensions when running the TestApp
- Added `modify` support for PageExtensions
- Changes in the TestApp:
- Added a Page with views
- Added Views to a Page Extension
- Fixed some AL Warnings that wasn't visible before when AL Language extension was disabled
- Updated documentation
The other problems that are mentioned in #288 will be tracked in other issues.
After the changes in this PR, I can parse the complete Base Application without any stopping …
> Support Page Views

- extension/src/NABfunctions.ts
- extension/src/PowerShellFunctions.ts
- extension/src/VSCodeFunctions.ts
- extension/src/extension.ts
This mainly to illustrate my idea dividing the code to more separated areas of responsibility, or legs, or domains or whatever would be the best word. As this PR doesn't contribute much more value than the start and template of that idea, it's totally fine if we discard it :)
- Move PowerShell functions from `NABFunctions.ts` to `PowerShellFunctions.ts`.
- Move function `showErrorAndLog` from `NABFunctions.ts` to `VSCodeFunctions.ts` as it's now shared.
- In `extension.ts` declare PowerShell commands in a new array `powerShellFunctions` and join it with `commandlist`.
I have limited ability to test this but I've ensured that commands from both arrays are triggered.
> Refactor: Powershell functions

- extension/src/NABfunctions.ts
Fixes #289 .
- Reject promise on error in `NABFunctions.generateExternalDocumentation` and `NABFunctions.generateToolTipDocumentation()`.
> Catch error and reject promise on functions run with progress

- extension/CHANGELOG.md
- extension/src/FileFunctions.ts
- extension/src/test/Template.test.ts
- extension/src/test/resources/templateSettings/files/App/.vscode/settings.json
- extension/src/test/resources/templateSettings/files/al.template.json
Fixes #303 .
- Folders with a dot prefix in the name was excluded when matching glob patterns.
- Hardcoded to always exclude the `.git` folder, since that could be a straight way to disaster...
- Added .vscode/settings.json to the test for this
- Changelog
> fix: Template substitutions inside .vscode folder

- .github/workflows/nerd-stuff.yml
- extension/src/LanguageFunctions.ts
- extension/src/NABfunctions.ts
- extension/src/test/Settings/CliSettingsLoader.test.ts
- extension/src/test/Template.test.ts
Fixes #311  .
- Generate and upload coverage report before running check. This will ensure that the artifact is available even if the threshold check fails.
- Added a few tests to make up for the threshold.
> ci: upload coverage before running check

- extension/package.json
- extension/src/ALObject/ALElementTypes.ts
- extension/src/ALObject/Enums.ts
- extension/src/ALObject/Maps.ts
- extension/src/NABfunctions.ts
- extension/src/Settings/Settings.ts
- extension/src/extension.ts
Fixes #322.
- A new command to create a permission set with 
- All objects in the current workspace folder
- Objects with `ObsoleteState = Removed ` is ignored
- All objects are added with "X" permissions
- TableData are added with "RIMD" permissions
> feat: Create Permission Set

- extension/package-lock.json
- extension/package.json
- extension/src/test/runTest-coverage.ts
- extension/src/test/runTest.ts
According to the [release notes for VSCode 1.65](https://code.visualstudio.com/updates/v1_65#_vscodetest-package-renamed-to-vscodetestelectron), we should replace our devDependendcies to use `@vscode/test-electron` instead of `vscode-test`.
- Removed dependency on `vscode-test`
- Added dependency on `@vscode/test-electron`
- Updated test runner code to use new dependency
> ci: use @vscode/test-electron

- extension/CHANGELOG.md
- extension/src/ALObject/ALParser.ts
- extension/src/constants.ts
- extension/src/test/ALObjectTestLibrary.ts
- extension/src/test/ALParser.test.ts
Fixes #326.
- Improved parsing of Enum values with captions written on one line, including comments.
- Instead of using custom caption parsing for enum values, the ordinary caption parser is now used.
> fix: Parsing Enum values one-liners #326

- extension/src/NABfunctions.ts
- extension/src/PermissionSet/PermissionSetFunctions.ts
- extension/src/PermissionSet/PermissionSetNamePanel.ts
- extension/src/Settings/Settings.ts
- extension/src/Settings/SettingsLoader.ts
- extension/src/Settings/SettingsMap.ts
- extension/src/WorkspaceFunctions.ts
- extension/src/test/PermissionSet.test.ts
- Support for mandatoryPrefix in AppSourceCop.json
- Support conversion of PermissionSet for apps not in the first workspace folder - #334
- Support for the AL Language extension setting al.packageCachePath - #335
> feat: PermissionSet conversion for non-first app folders and with al.packageCachePath

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
I do not like the auto-closing of issues from PR with the `Fixes #XXX`...
Now that we've got the pre-release feature, I prefer to release any fix as pre-release and then wait for feedback before closing the issue. 
When we get the pipelines for Pre-Release and Release in place we could automate the flow a bit with Labels.
Manually set `Label:Ships in future version` -> [pre-release pipeline] -> `Label:Pre-Release` -> [release pipeline] -> `Label:Shipped`
- Updated PR template to not auto-close issues
- Update issue templates
- Auto-set labels (we can remove or change on issue if needed)
What do you think?
> chore: Updated GitHub templates

- extension/src/Error.ts
- extension/src/FileFunctions.ts
- extension/src/NABfunctions.ts
- extension/src/WorkspaceFunctions.ts
- extension/src/Xliff/XLIFFDocument.ts
- extension/src/externalresources/ExternalResources.ts
- extension/src/test/XLIFFTypes.test.ts
- extension/src/test/XlfHighlighter.test.ts
A few issues that was identified by analyzing telemetry has been fixed
- Check if a file exists before deleting
- Log json syntax errors to better understand what kind of issues we need to address
- Skip some unnecessary telemetry logging of exceptions (more or less expected errors)
- Improved some error message
- Throw error if xlf file is empty
- Handle some error of xlf file syntax
> fix: Handle errors from Telemetry

- extension/src/constants.ts
- extension/src/test/ALParser.test.ts
- extension/src/test/PermissionSet.test.ts
- Added support for Lists with Dictionary like `List of [Dictionary of [Integer, Code[20]]]` and alike
The regex constants is getting even worse. This was because I already had support for Dictionaries with Lists and ended up with an endless loop... 😅
This might be refactored one day to use a recursive function to build this regex with support for n levels of nested dictionaries and/or lists. But I think this is enough for now. I believe that I successfully parsed the complete BaseApp with this change.
Known limitation: We do not support "Dictionaries with Lists of Dictionaries", or "Lists with Dictionaries of Lists" and similar constructs.
> fix: Support List of Dictionary

- .github/workflows/nerd-stuff.yml
VS Code 1.66  bumps Nodejs version to 16.x.
> ci: bump node version 14.x->16.x

- extension/src/XliffFunctions.ts
- extension/src/test/bugs/333.test.ts
Related to #333 .
- Only increase numberOfReviewsAdded based on needsReview() === true
> refactor: use ternary instead of if-statement to increase value

- extension/CHANGELOG.md
- extension/README.md
- extension/package.json
- extension/src/Settings/Settings.ts
- extension/src/Settings/SettingsMap.ts
- extension/src/WorkspaceFunctions.ts
Related to #345 .
- Added a new setting, `TranslationFilenamePattern`, that can be used to limit the matching of xlf files when performing xliff related tasks.
- Instead of adding the setting as an array of patterns that should be ignored (as requested in issue), I decided to add a pattern for the files that should be used.
> feat: TranslationFilenamePattern setting

- extension/package-lock.json
- extension/package.json
- extension/tsconfig.json
So this might be a bit scary but all seems fine on my end;
:heavy_check_mark:  installs
:heavy_check_mark:  compiles
:heavy_check_mark:  tests; passing :ok_hand: 
(cleared `out`, `dist` and `node_modules` before hand)
- Bump target to `es2020`
- Removed some libs
- Remove some deprecated and unnecessary dependencies.
> build: clean up dependencies

- .github/workflows/publish.yml
- extension/package-lock.json
- extension/package.json
- Use PAT for git commands, to enable push to master
This is just temporary, we should switch to creating a release branch to trigger this workflow, and then auto complete a PR back to master.
> ci: Enable forced push to master

- extension/CHANGELOG.md
- extension/src/Template/TemplateFunctions.ts
- extension/src/test/DocumentFunctions.test.ts
Related to #343.
- Support for brackets ([ and ]) in folder or file names when using the template features
> fix: Support brackets in path names for templates

- extension/CHANGELOG.md
- extension/src/Common.ts
- extension/src/Template/TemplatePanel.ts
- extension/src/Template/TemplateTypes.ts
- extension/src/XliffEditor/HTML.ts
- extension/syntaxes/templateSettingsSyntax.json
Related to #365 .
- `asdf <a.b@c.d>` only shows as `asdf`
The other things in #365 will wait until #324 is completed :)
> feat: AL Template improvements

- extension/src/Dictionary.ts
- extension/src/test/Common.test.ts
- extension/src/test/Dictionary.test.ts
- extension/src/test/FileFunctions.test.ts
- extension/src/test/resources/invalid-json.json
Adding missing tests.
- Removes unused `exists` function in Dictionary.ts
- Adds tests for `htmlEscape` and `htmlUnescape` in Common.ts
- Adds test for error path of `loadJson` of FileFunctions.ts
> test: some unit tests

- extension/src/test/SymbolReference/SymbolReferenceCache.test.ts
- extension/src/test/Xliff/XliffCache.test.ts
Closes #375.
- Improve testing of branches in XliffCache & SymbolReferenceCache
> Testing of cache branches

- extension/src/NABfunctions.ts
- extension/src/Settings/SettingsLoader.ts
- extension/src/Template/TaskRunner.ts
- extension/src/test/TaskRunner.test.ts
Related to #324 .
I that this one is on me, since I tricked you into this, @theschitz ...
But `getWorkspaceFolderPath()` did not do what I thought it did... 
I added `WorkspaceFileFolderPath()` that will return the folder of the workspace file, with a fallback to `getWorkspaceFolderPath()`, if no workspace file is being used.
I've tested it a few times, and now it seems to work.
PS. This "fire & forget" thing is really interesting, far from all commands implement the async part in a perfect way... 😂
So even if we do our best to await, it most probably wont wait until the complete command is finished. But I'd say that this is as good as it gets on this approach. 
And I quickly found out that I want the parameters for this... I believe that we could create a few PRs to Waldo, to improve his …
> fix: WorkspaceFileFolderPath for TaskRunner

- .github/workflows/tests.yml
- Run tests against Node.js 18.x which is has active LTS start on 2022-10-25.
- https://nodejs.org/en/about/releases/
- Removes Node.js 14.x from the matrix.
> ci: run tests against node 18.x which next LTS version.

- extension/CHANGELOG.md
- extension/src/ALObject/Enums.ts
- extension/src/ALObject/Maps.ts
- extension/src/PermissionSet/PermissionSetFunctions.ts
- extension/src/PermissionSet/XmlPermissionSet.ts
- extension/src/test/PermissionSet.test.ts
- extension/src/test/resources/permissionset/permissionSet.xml
- extension/src/test/resources/permissionset/permissionSet2.xml
- extension/src/test/resources/permissionset/permissionSet3.xml
- test-app/Xliff-test/app.json
Related to #384 .
- Support for the XML Permission Set format generated when exporting a Permission Set from the Web Client.
- Support for `TenantPermissions` elements
- Support for permissions on `System`
- Support for names instead of numbers in `ObjectType`
- Support for `Yes` and `Indirect` instead of numbers for the different permissions
- Support for missing permission elements
> fix: Support XmlPermissionSet exported from Client

- extension/CHANGELOG.md
- extension/src/Template/TemplateFunctions.ts
Related to #388 .
- Changed implementation of toLowerCase from https://docs-lodash.com/v4/lowercase/, to regular string.toLocaleLowerCase(), since the lodash implementation added spaces :)
- Similar change to toUpperCase
- Support for omitted createXlfLanguages element
> fix: Transform with Remove spaces and then Lowercase

- extension/src/PowerShellFunctions.ts
A common case where certificates subject begins with other properties then CN. This change will support them as well. For example, our sign certificate subject is `E=d365support@theta.co.nz, CN=Theta Systems Limited, OU=Dynamics 365, O=Theta Systems Limited, L=Auckland, S=Auckland, C=NZ`
Related to #397 .
> fix: Support for "E" tag in certificate subject

- extension/package-lock.json
- extension/package.json
- extension/src/FileFunctions.ts
- extension/src/NABfunctions.ts
- extension/src/PermissionSet/PermissionSetFunctions.ts
- extension/src/PermissionSet/PermissionSetNamePanel.ts
- extension/src/Troubleshooting.ts
- extension/src/Xliff/XLIFFDocument.ts
- extension/src/cli/CreateDocumentation.ts
- extension/src/cli/RefreshXLF.ts
- extension/webpack.config.js
- Seems as TS Lint has changed some behavior on implicit casting, now requiring explicit casts for error variables
- Updated dependencies to latest
- The dependencies for ApplicationInsights messed up webpack, so I had to add a couple of exceptions in webpack config.
> fix: webpack omit opentelemetry and explicit casting

- extension/package-lock.json
- extension/package.json
- extension/src/ALObject/ALXmlComment.ts
Supersedes #414 
- Bumps [@xmldom/xmldom](https://github.com/xmldom/xmldom) from 0.7.5 to 0.7.9.
- More information found in #414
I had to add a workaround to transform xml comments with multiple root elements to a well-formed xml.
> build(deps): bump @xmldom/xmldom to 0.7.9

- extension/CHANGELOG.md
- extension/src/Xliff/XLIFFDocument.ts
- extension/src/test/ExternalResources.test.ts
- extension/src/test/Xliff/TransUnit.test.ts
Related to #424.
- Supports the "approved" attribute in trans-unit elements
> feat: Support for "approved" attribute in Xliff trans-unit

- extension/.nycrc.json
- extension/CHANGELOG.md
- extension/README.md
- extension/package.json
- extension/src/ALObject/ALProcedure.ts
- extension/src/ALObject/Enums.ts
- extension/src/Documentation.ts
- extension/src/Settings/Settings.ts
- extension/src/Settings/SettingsMap.ts
- test-app/Xliff-test/.vscode/settings.json
- test-app/Xliff-test/docs/info.json
- test-app/Xliff-test/docs/report-nab-test-report/index.md
- test-app/Xliff-test/docs/report-nab-test-report/test-method.md
- test-app/Xliff-test/docs/reportextension-nab-test-report-ext/index.md
- test-app/Xliff-test/src/TestReport.Report.al
- test-app/Xliff-test/src/TestTable.Table.al
Related to #492 .
- New Features:
- Added a new setting, `NAB.documentation.includeAllProcedures`. When creating external documentation, this setting specifies if all procedures should be included. If not enabled, only public procedures will be included.
- Added a new setting, `NAB.documentation.includeReports`. When creating external documentation, this setting specifies if Reports should be included. If not enabled, only Reports with public (or any, if `NAB.documentation.includeAllProcedures` is enabled) procedures will be included.
- Added a new setting, `NAB.documentation.includeXmlPorts`. When creating external documentation, this setting specifies if XmlPorts should be included. If not enabled, only XmlPorts with public (or any, if …
> feat: Settings for documentation objects #492

- extension/src/XliffFunctions.ts
- extension/src/test/bugs/333.test.ts
- extension/src/test/bugs/469.test.ts
Adjust the handling of the target element when the source is empty during the refresh of XLF files. 
This change ensures that the REVIEW tag is only added when appropriate, addressing the issue where it was incorrectly applied regardless of the target's state.
Fixes #469
> Fix REVIEW tag behavior when source is empty

- extension/package.json
- extension/src/ChatTools/GetTranslatedTextsByStateTool.ts
- extension/src/test/ChatTools/GetTranslatedTextsByStateTool.test.ts
The optional SourceText parameter filter results to only include translations that match this exact source text.
This is particularly useful for:
1) Finding all translations of a specific phrase or term across different contexts
2) Reviewing translation consistency for repeated text
3) Updating all occurrences of a specific source text during translation review.
For example, use 'Customer' to find all translations where the source text is exactly 'Customer', or 'Enter a value' to find translations of that specific instruction text.
> feat: Added Source Text as optional filter to the GetTranslatedTextsByState Tool

- extension/MCP_SERVER.md
- extension/package.json
- extension/src/ChatTools/GetTextsByKeywordTool.ts
- extension/src/ChatTools/shared/XliffToolsCore.ts
- extension/src/extension.ts
- extension/src/mcp/server.ts
- extension/src/test/ChatTools/GetTextsByKeywordTool.test.ts
This pull request introduces a new feature that allows users to search for source texts in XLF files by keyword or regular expression, returning matching translation units (including untranslated ones). The update includes the implementation of the core logic, integration with the MCP server and chat tools, schema updates, documentation, and comprehensive tests. Additionally, some minor improvements and clean-up were made to related schemas and documentation.
The most important changes are:
**New Feature: Search Texts by Keyword/Regex**
- Implemented `getTextsByKeywordCore` in `XliffToolsCore` to search XLF files for source texts matching a keyword or regex, supporting pagination, case sensitivity, and regex options. Returns translation units with metadata.
- Added `GetTextsByKeywordTool` …
> feat: getTextsByKeyword tool
